### ISSUE TITLE
Suggestion: proposed change <h1> and <a> tag color

### ISSUE THREAD

**Issue by dtmajesty** [llpyyz/github-crash-course-udemy-maxs#1]
I think the main title and anchor tags should be a different color:

```css

h1 {
  color: #b3b2e8;
}

a {
  color: #fe89d9;
}

```
